name: fluttermay
description: "Tamays Flutter Extensions"
version: 0.0.9
homepage: https://github.com/tamaygz/fluttermay

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.19.0
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
