name: fluttermay
description: "Tamays Flutter Extensions"
version: 0.0.2
homepage: https://github.com/tamaygz/fluttermay

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.20.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: